apiVersion: nr-alerts.k8s.newrelic.com/v1
kind: NrqlAlertCondition
metadata:
  name: my-alert
spec:
  nrql:
    query: "SELECT count(*) FROM Transactions"
    since_value: "10"
  enabled: true
  terms:
    - threshold: "75.0"
      time_function: "all"
      duration: "5"
      priority: "critical"
      operator: "above"
  name: "K8s generated alert condition"
  existing_policy_id: 26458
  region: "staging"
  api_key_secret:
    name: nr-api-key
    namespace: default
    key_name: api-key

---
apiVersion: nr-alerts.k8s.newrelic.com/v1
kind: NrqlAlertCondition
metadata:
  name: my-alert
spec:
  nrql:
    query: "SELECT count(*) FROM Transactions"
    since_value: "10"
  enabled: true
  terms:
    - threshold: "75.0"
      time_function: "all"
      duration: "5"
      priority: "critical"
      operator: "above"
  name: "K8s generated alert condition"
  existing_policy_id: 32669
  api_key: "API_KEY"
  region: "staging"
