
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nr-alerts-k8s-newrelic-com-v1-nrqlalertcondition
  failurePolicy: Fail
  name: mnrqlalertcondition.kb.io
  rules:
  - apiGroups:
    - nr-alerts.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nrqlalertconditions

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-nr-alerts-k8s-newrelic-com-v1-nrqlalertcondition
  failurePolicy: Fail
  name: vnrqlalertcondition.kb.io
  rules:
  - apiGroups:
    - nr-alerts.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nrqlalertconditions
