# permissions for end users to view alertschannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertschannel-viewer-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertschannels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertschannels/status
  verbs:
  - get
