# permissions for end users to view apmalertconditions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apmalertcondition-viewer-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - apmalertconditions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - apmalertconditions/status
  verbs:
  - get
