# permissions to do viewer policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-viewer-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - policies/status
  verbs:
  - get
