# permissions to do viewer alertsnrqlconditions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertsnrqlcondition-viewer-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertsnrqlconditions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertsnrqlconditions/status
  verbs:
  - get
