# permissions to do edit newrelicpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelicpolicy-editor-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - newrelicpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - newrelicpolicies/status
  verbs:
  - get
  - patch
  - update
