# permissions to do edit nrqlalertconditions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nrqlalertcondition-editor-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions/status
  verbs:
  - get
  - patch
  - update
