# permissions to do viewer nrqlalertconditions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nrqlalertcondition-viewer-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions/status
  verbs:
  - get
