
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nr-alerts.k8s.newrelic.com
  resources:
  - nrqlalertconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr-alerts.k8s.newrelic.com
  resources:
  - nrqlalertconditions/status
  verbs:
  - get
  - patch
  - update
