apiVersion: v1
kind: Secret
metadata:
  name: nr-api-key
  namespace: default
type: Opaque
stringData:
  api-key: <your New Relic personal API key>
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: default
type: Opaque
stringData:
  token: super-secret-example-header-token
