# Note: If using a k8s secret, remove `api_key`, uncomment `api_key_secret`,
# add your API key to examples/example_secret.yaml, and run
# `kubectl apply -f examples/example_secret.yaml`

apiVersion: nr.k8s.newrelic.com/v1
kind: AlertsPolicy
metadata:
  name: my-policy
spec:
  account_id: <your New Relic account ID>
  api_key: <your New Relic personal API key>
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  name: k8s created policy
  incidentPreference: "PER_POLICY"
  region: "US"
  conditions:
    - spec:
        type: "NRQL"
        nrql:
          query: "SELECT count(*) FROM Transactions"
          evaluationOffset: 10
        enabled: true
        terms:
          - threshold: "75.0"
            threshold_occurrences: "ALL"
            threshold_duration: 60
            priority: "CRITICAL"
            operator: "ABOVE"
        name: "nrql condition"
        violationTimeLimit: "ONE_HOUR"
        valueFunction: "SINGLE_VALUE"
    - spec:
        type: "apm_app_metric"
        enabled: true
        metric: "apdex"
        condition_scope: application
        entities:
          - "215037795"
        apm_terms:
          - threshold: "0.9"
            time_function: "all"
            duration: "5"
            priority: "critical"
            operator: "above"
        name: "apm condition"
