# Note: If using a k8s secret, remove `api_key`, uncomment `api_key_secret`,
# add your API key to examples/example_secret.yaml, and run
# `kubectl apply -f examples/example_secret.yaml`

apiVersion: nr.k8s.newrelic.com/v1
kind: AlertsAPMCondition
metadata:
  name: alert-1029267
spec:
  account_id: <your New Relic account ID>
  api_key: <your New Relic personal API key>
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  type: "apm_app_metric"
  enabled: true
  metric: "apdex"
  condition_scope: application
  entities:
    - "215037795"
  apm_terms:
    - threshold: "0.9"
      time_function: "all"
      duration: "5"
      priority: "critical"
      operator: "above"
  name: "K8s generated apm alert condition"
  # Must reference an existing New Relic alert policy from your account
  existing_policy_id: "897188"
  region: "US"
