apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- example_policy.yaml
patchesStrategicMerge:
- development/personal-api-key-patch.yaml
- development/personalized-policy-name-patch.yaml
- development/use-staging-patch.yaml
